/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Desk(props) {
  const { nodes, materials } = useGLTF("models/desk.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.55, 0.7]} rotation-y={-Math.PI / 2} scale={1.05}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.MetalBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials.DeskWood}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/desk.gltf");
